metadata:
  author: Rivo Juicer Wowor (00000059635)
  fontfamily: plex-otf

pdf-engine: xelatex
citeproc: true
csl: ${.}/ref/apa.csl 
bibliography: ${.}/ref/library.bib
template: ${.}/ref/default.tex
